### ISSUE TITLE
Able to use command anywhere within message

### ISSUE THREAD

**Issue by NeutronicMC** [OwenCalvin/discord.ts#12]
If a command prefix is found anywhere within a message (not just the beginning) the command still executes.

**Comment by OwenCalvin** [comment]
Thank’s for sharing your issue, could you please provide a simple example to reproduce ?

**Comment by OwenCalvin** [comment]
When you use a function to return the prefix you must explicitly put `^` before the prefix event if it's string:
```ts
function(command: CommandMessage) {
  switch(command.guild.name) {
    case "guildA":
      return "^!";
    case "guildB":
      return "^.";
  }
}

@Discord(dynamicPrefix)
class MyBot {
  // ...
}
```
