### ISSUE TITLE
function required to read command arguments separately  

### ISSUE THREAD

**Issue by oceanroleplay** [OwenCalvin/discord.ts#14]
this is example of command

when we define command name without slug like
> @Command("cmd")
// and then we retrieve it with ```command.commandName``, it returns
 cmd

but when we do the same thing with arguments
> @Command("cmd :slug")
and then we retrieve it with ```command.commandName``, it returns
> cmd :slug

in runtime command name is ``cmd``. There should be solution to get command name and arguments separately

**Suggested solution:**  return command name with `command.commandName` but make another function `command.commandArguments` which returns the arguments in array format.

> //command.commandName
> cmd
>
> //command.commandArguments
>['slug']

**Comment by ebox86** [comment]
Any update on this? i hit the same problem today.

**Comment by AndyClausen** [comment]
Should not be a problem in slash commands version (5.x)

**Comment by vijayymmeena** [comment]
### Closed

Reason: package is not maintained regularly.
