### ISSUE TITLE
Args as array

### ISSUE THREAD

**Issue by quinnvaughn** [OwenCalvin/discord.ts#27]
Is there an easy way to just get the args as one array? Adding an actual :args only gets the first or however many, but I'm looking for an indeterminant amount of inputs (well up to 5).

**Comment by iDavidB** [comment]
Do you have an example of how you think this would work? 

My first thought would assume something like this:
```ts
// Message: -command May the force be with you
const args = message.args

args[0] = may
args[1] = the
args[2] = force
...
```
But this still has many questionable issues with it.

**Comment by quinnvaughn** [comment]
I would think you'd specify in the string and it would check for that. 

Something like 

`
@Command("create :type\array :name")
`

Wouldn't have to be exactly that, but just some wording it would parse for to let it be known that it's an array (the type arg in this example).

**Comment by quinnvaughn** [comment]
Right now what I'm doing is taking multiple inputs by splitting the command after the command text, and then regexing it by strings enclosed in double-quotes, but I think this library probably could do that automatically for us.

**Comment by AndyClausen** [comment]
I agree that when something is surrounded by quotes, it should be parsed as a single arg. However, I don't think parsing multiple args as an array is realistic. Maybe edit the issue to only be about quoted args?

**Comment by AndyClausen** [comment]
This should be fixed in the slash commands version (5.x) 🙂
