### ISSUE TITLE
bigint support

### ISSUE THREAD

**Issue by Pho3niX90** [OwenCalvin/discord.ts#28]
Simple example:

    @Command("find :search")
    async execute(command: CommandMessage) {
        const search = command.args.search;
        console.log("test " + search);
    }

`find 76561198007433923` would yield `test 76561198007433920`

**Comment by ramarivera** [comment]
I found the same problem today, I ended up prefixing my arguments with another symbol, which is less than ideal

**Comment by iDavidB** [comment]
I think this is mostly just an issue with the fact that every integer arg is automatically converted to an actual integer. Wouldn't this behavior be solved by always passing the arg on as a string and letting the consuming function decide what to do with it?

**Comment by Pho3niX90** [comment]
@iDavidB it would definitely solve the issue at hand.

**Comment by Pho3niX90** [comment]
fixed in https://github.com/OwenCalvin/discord.ts/pull/31
