### ISSUE TITLE
can't inject Client on @On("ready")

### ISSUE THREAD

**Issue by mathias-poweredsoft** [OwenCalvin/discord.ts#38]
the client is undefined when injected in the ready event. I'm trying to create a channel if it doesn't exist when my bot startup.

**Comment by SteeledSlagle13** [comment]
can u post a snippet of your code

**Comment by SteeledSlagle13** [comment]
```ts
@Once("ready")
onReady([]: ArgsOf<"ready">, client: Client): void {
  //client stuff
}
 ```
 is how you can do that with the client injection
 https://github.com/OwenCalvin/discord.ts#client-payload-injection

**Comment by mathias-poweredsoft** [comment]
Sorry for the late response. I was missing the []: ArgsOf<"ready"> first part.

Thank You

**Comment by SteeledSlagle13** [comment]
np :D
