### ISSUE TITLE
Add support for slash commands

### ISSUE THREAD

**Issue by AndyClausen** [OwenCalvin/discord.ts#42]
This has not yet been implemented (properly) in discord.js, [but it is on its way](https://github.com/discordjs/discord.js/pull/5106). I'm creating this issue to start a discussion and make sure there is some attention on it.

I think this is a great opportunity to utilize the `@Infos`/`@Description` decorators 🙂

**Comment by SteeledSlagle13** [comment]
Will have more info when discord js adds full support in discord.js v13

**Comment by AndyClausen** [comment]
Update: [this new PR](https://github.com/discordjs/discord.js/pull/5448) has superseded the other one.

**Comment by AndyClausen** [comment]
I guess this could be closed, or should we wait for v13?

**Comment by OwenCalvin** [comment]
It's done :) !
https://owencalvin.github.io/discord.ts/
