### ISSUE TITLE
Can't find a way to post an embeded message

### ISSUE THREAD

**Issue by Anshrk** [OwenCalvin/discord.ts#47]
I couldn't find a way to send embed message,
i created an embed using discord.js but couldn't send it cause
```ts
channel.send()
```
didn't have an `embed` parameter

**Comment by AndyClausen** [comment]
This is not a feature specific for discord.ts, but rather discord.js as you said yourself.
`channel.send` takes a parameter of either a string or obj. To send an embed, do `channel.send({embed: myEmbed})`.
Please check out [the discord.js docs](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=send), it will answer most questions like this one.

**Comment by Anshrk** [comment]
oh, that works, thank you for the help
