### ISSUE TITLE
The slash command does not execute correctly

### ISSUE THREAD

**Issue by cristianireyes** [OwenCalvin/discord.ts#50]
I am testing the forward slash commands with the following example project: https://github.com/OwenCalvin/discord.ts-starter.git

> Also update the `@typeit/discord` dependency to its latest available version: **5.0.11**

```json
{
  "dependencies": {
    "@typeit/discord": "^5.0.11",
    "discord.js": "github:discordjs/discord.js",
    "reflect-metadata": "^0.1.13"
  },
  "devDependencies": {
    "@types/node": "^15.6.0",
    "ts-node": "^9.1.1",
    "tslib": "^2.2.0",
    "typescript": "^4.2.4"
  }
}
```

The problem I found is when executing a command within a group. It seems that the command tree cannot be calculated correctly and returns undefined.
For better understanding I provide screenshots of debugging.

### Analysis:

1. I run my command on my discord server
![1](https://user-images.githubusercontent.com/34529231/120834535-8891db00-c539-11eb-8c66-1e0a1e63b80c.png)

2. The interaction arrived successfully and get the interaction group tree
![2](https://user-images.githubusercontent.com/34529231/120831975-837f5c80-c536-11eb-94a5-cbaf421a8978.png)

3. At this point, when trying to execute the getOptionsTree method on line 223, the variable _a takes the value of undefined in its second iteration
![3](https://user-images.githubusercontent.com/34529231/120833018-aa8a5e00-c537-11eb-947e-07ed49f34011.png)
![3bis](https://user-images.githubusercontent.com/34529231/120833033-afe7a880-c537-11eb-8fa6-ba47d57e11ac.png)

4. And finally the getInteractionGroupTree method ends up returning the following
![4](https://user-images.githubusercontent.com/34529231/120833332-08b74100-c538-11eb-93fd-c2bec03ba070.png)

5. Then it tries to retrieve slash from tree, accessing by case 1, but the conditions are never met because it tries to compare the group name with the command name, which is wrong
![5](https://user-images.githubusercontent.com/34529231/120834125-fee20d80-c538-11eb-8c93-e7271985289c.png)

6. And consequently, it ends up returning slash undefined
![6](https://user-images.githubusercontent.com/34529231/120834323-3d77c800-c539-11eb-8173-5492c4f23c52.png)

This causes the command to fail by not executing the slash
![7](https://user-images.githubusercontent.com/34529231/120834466-6b5d0c80-c539-11eb-8288-1e7e758f0ccb.png)

> Try to be as detailed as possible so that I can share my analysis.

Thanks for your time
Regards ✌🏻

**Comment by owengombas** [comment]
Thank's !

discord.**js** changed the options field from an array to a `Map`, it causes this issue, I fixed it you can now update the package by running `npm run update` and verify that your version is now 5.0.12 !

:)

**Comment by cristianireyes** [comment]
> Thank's !
> 
> discord.**js** changed the options field from an array to a `Map`, it causes this issue, I fixed it you can now update the package by running `npm run update` and verify that your version is now 5.0.12 !
> 
> :)

Thanks for your quick resolution. Works!

![works](https://user-images.githubusercontent.com/34529231/120848387-1de99b00-c54b-11eb-8ba4-aa1cc45b6682.png)
