### ISSUE TITLE
Template not avaiable

### ISSUE THREAD

**Issue by Thoemmy** [OwenCalvin/discord.ts#68]
git clone https://github.com/owencalvin/discord.js-template

Isn't avaiable anymore.

**Comment by vijayymmeena** [comment]
that's actually https://github.com/owencalvin/discord.ts-template

Also consider this example, https://github.com/oceanroleplay/discord.ts-example

**Comment by Thoemmy** [comment]
Thx :) , i totaly forgot to close the issue
